#!/bin/bash

echo "=== Instrucciones para configurar manualmente el Asistente Virtual de Salud Mental ==="
echo ""
echo "1. Crea un entorno virtual con el siguiente comando:"
echo "   python3 -m venv venv"
echo ""
echo "2. Activa el entorno virtual:"
echo "   source venv/bin/activate"
echo ""
echo "3. Instala las dependencias:"
echo "   pip install -r requirements.txt"
echo ""
echo "4. Ejecuta la aplicación:"
echo "   streamlit run app.py"
echo ""
echo "5. Cuando termines, desactiva el entorno virtual:"
echo "   deactivate"
echo ""
echo "Nota: Si no tienes python3-venv instalado, puedes instalarlo con:"
echo "sudo apt-get update && sudo apt-get install -y python3-venv" 